In [59]:
nbits = 3  # number of hyperplanes and binary vals to produce
d = 64  # vector dimensions

In [60]:
import numpy as np
np.random.seed(0)
# create a set of 4 hyperplanes, with 2 dimensions
#  -.5 to center our array values around the origin (0, 0).
plane_norms = np.random.rand(nbits, d) - .5
plane_norms

array([[ 0.0488135 ,  0.21518937,  0.10276338,  0.04488318, -0.0763452 ,
         0.14589411, -0.06241279,  0.391773  ,  0.46366276, -0.11655848,
         0.29172504,  0.02889492,  0.06804456,  0.42559664, -0.42896394,
        -0.4128707 , -0.4797816 ,  0.33261985,  0.27815675,  0.37001215,
         0.47861834,  0.29915856, -0.03852064,  0.28052918, -0.38172557,
         0.13992102, -0.35664671,  0.44466892,  0.02184832, -0.08533806,
        -0.23544439,  0.27423369, -0.04384967,  0.06843395, -0.4812102 ,
         0.1176355 ,  0.11209572,  0.116934  ,  0.44374808,  0.1818203 ,
        -0.1404921 , -0.06296805,  0.1976312 , -0.43977453,  0.16676672,
         0.17063787, -0.28961744, -0.3710737 , -0.18457165, -0.13628923,
         0.07019677, -0.06139849,  0.48837384, -0.39795519, -0.29112324,
        -0.33869048,  0.15310833, -0.2467084 , -0.03368923, -0.25557441,
        -0.34103042, -0.38962486,  0.15632959, -0.36181705],
       [-0.30341764, -0.13127483,  0.32099323, -0.40289872,  0.

In [61]:
a = np.random.rand(d)
b = np.random.rand(d)
c = np.random.rand(d)
dataset=[a,b,c]

In [62]:
a_dot = np.dot(a, plane_norms.T)
b_dot = np.dot(b, plane_norms.T)
c_dot = np.dot(c, plane_norms.T)
a_dot

array([ 0.16080958, -0.4788989 ,  0.76902844])

In [63]:
a_dot = a_dot > 0
b_dot = b_dot > 0
c_dot = c_dot > 0
c_dot

array([False, False, False])

In [64]:
a_dot = a_dot.astype(int)
b_dot = b_dot.astype(int)
c_dot = c_dot.astype(int)
a_dot

array([1, 0, 1])

In [66]:
vectors = [a_dot, b_dot, c_dot]
buckets = {}  # hash table
i = 0

for i in range(len(vectors)):
    # convert from array to string
    hash_str = ''.join(vectors[i].astype(str))
    # create bucket if it doesn't exist
    if hash_str not in buckets.keys():
        buckets[hash_str] = []
    # add vector position to bucket
    buckets[hash_str].append(i)

print(buckets)

{'101': [0, 1], '000': [2]}


In [77]:
def HammingDistance(s1: str, s2: str) -> int:
    """ Compute the Hamming distance between two bitstrings """
    assert len(s1) == len(s2)
    dist = 0
    for i in range(len(s1)):
        if s1[i] != s2[i]:
            dist += 1
    return dist

In [78]:
def find_closest_bucket(query_hash_str, buckets):
    if query_hash_str in buckets:
        return buckets[query_hash_str]
    else:
        # Find the closest bucket using Hamming distance
        min_distance = float('inf')
        closest_bucket = None
        for bucket_key in buckets.keys():
            distance = HammingDistance(query_hash_str, bucket_key)
            if distance < min_distance:
                min_distance = distance
                closest_bucket = buckets[bucket_key]
        return closest_bucket

In [ ]:

query=np.random.random(64)
# print(query)

query_dot = np.dot(query, plane_norms.T)
query_dot = query_dot > 0
query_dot = query_dot.astype(int)
print(query_dot)
# Convert the query array to a string
query_hash_str = ''.join(query_dot.astype(str))

# Check which bucket the query belongs to
if query_hash_str in buckets.keys():
    bucket_containing_query = buckets[query_hash_str]
    min_dist=100
    index=-1
    for vec in bucket_containing_query:
          ## compute cosine similarity
          dot_res=np.dot(query,dataset[vec].T)
          print(dot_res)
          res = dot_res / (np.linalg.norm(query) * np.linalg.norm(dataset[vec].T))
          if res<min_dist:
              min_dist=res
              index=vec

    print(index)

    print("Query belongs to bucket:", bucket_containing_query)
else:
    bucket=find_closest_bucket(query_hash_str, buckets)

[0 1 1]
